### ISSUE TITLE
decorations_theme_variant: unknown variant `dark`, expected `Light` or `Dark`

### ISSUE THREAD

**Issue by philipborg** [CachyOS/cachyos-gnome-settings#2]
![image](https://user-images.githubusercontent.com/1827607/229372760-09c813e7-a6b7-47e5-975b-1894d976bc3f.png)
In some terminals, such as the one opened by Cachy Kernel Manager, this error message shows. Occured on a fresh Gnome CachyOS installation.

**Comment by ptr1337** [comment]
Hi,

This is due the alacritty update. Somehow they deprecated "dark" and replaced it with "Dark". Not understandable.
We will fix this.

You need to fix this manually by changing the alacritty config in your home in line https://github.com/CachyOS/cachyos-gnome-settings/blob/develop/etc/skel/.config/alacritty/alacritty.yml#L33

**Comment by vnepogodin** [comment]
Hi

yes as was mentioned above we will fix that, but you will need either reinstall with online install or edit/copy manually

as it does get updated with the package update

**Comment by ptr1337** [comment]
Fixed. We will push soon the release to the repo.
https://github.com/CachyOS/cachyos-gnome-settings/commit/b693637203a4457e43994bfaaa27db4d44d76fc9

But since it is in your home folder, you need to modify it manually. The change will only affect fresh installation.

Thanks for reporting!

**Comment by philipborg** [comment]
Thanks for the fix! :smile:
